con_pro:con_pro.cpp
	g++ -g $^ -o $@ -lpthread
con_pro_sem:con_pro_sem.cpp
	g++ $^ -o $@ -lpthread
sem:sem.cpp
	g++ $^ -o $@ -lpthread
cond:cond.c
	gcc $^ -o $@ -lpthread
mutex:mutex.c
	gcc $^ -o $@ -lpthread
create:create.c
	gcc $^ -o $@ -lpthread
