ThreadPool:ThreadPool.cpp
	g++ $^ -o $@ -lpthread
con_pro:con_pro.cpp
	g++ -g $^ -o $@ -lpthread
con_pro_sem:con_pro_sem.cpp
	g++ $^ -o $@ -lpthread
new_cond:new_cond.c
	gcc $^ -o $@ -lpthread
new_mutex:new_mutex.c
	gcc $^ -o $@ -lpthread
found_mutex:found_mutex.cpp
	g++ $^ -o $@ -lpthread
sem:sem.cpp
	g++ $^ -o $@ -lpthread
cond:cond.c
	gcc $^ -o $@ -lpthread
mutex:mutex.c
	gcc $^ -o $@ -lpthread
create:create.c
	gcc $^ -o $@ -lpthread
